version: "3"

services:
  sonarqube:
    image: sonarqube
    restart: always
    ports:
      - "9001:9000"
    networks:
      - net
      - traefik_net
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

    labels:
      - traefik.enable=true
      - traefik.port=9000
      - traefik.docker.network=traefik_net
      - traefik.frontend.rule=PathPrefixStrip:/sonarqube/
  db:
    image: postgres
    networks:
      - traefik_net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./postgresql:/var/lib/postgresql
      - ./postgresql_data:/var/lib/postgresql/data

networks:
  net:
  traefik_net:
    external: true
