version: "3"
services:
  h2:
    image: oscarfonts/h2
    restart: always
    volumes:
      - ~/h2/data:/opt/h2-data
    environment:
      - JAVA_OPTS=-Xmx128m -Xms128m
      - H2_OPTIONS=-ifNotExists
    ports:
      - "1521:1521"
      - "81:81"
    networks:
      - net
    container_name: h2-instance
networks:
  net:
